center:
  x: 0
  z: 0
radius: 1000

spawnable-condition:
  n-above-air-blocks: 2
  n-below-opaque-blocks: 1

worldspawn-condition:
  n-above-air-blocks: 10
  n-below-opaque-blocks: 5
  y-upper-limit: 100
  y-lower-limit: 45